"""bids fingers crossed

Revision ID: 9b2b48228ec8
Revises: 0eac4de33ab9
Create Date: 2021-05-10 20:43:02.303315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2b48228ec8'
down_revision = '0eac4de33ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isAccepted', sa.Boolean(), nullable=True),
    sa.Column('eventId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    # ### end Alembic commands ###
