"""artist_name col added

Revision ID: 518dccb432ed
Revises: 9b2b48228ec8
Create Date: 2021-05-10 20:49:53.210659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518dccb432ed'
down_revision = '9b2b48228ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('artist_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'artist_name')
    # ### end Alembic commands ###
